### Récupérer un rapport de diabète pour un patient existant
GET http://localhost:8082/api/report/1
Accept: application/json

### Exemple de requête au patient-service
GET http://localhost:8080/api/patients/1
Accept: application/json

### Exemple de requête au note-service
GET http://localhost:8081/api/notes/patient/1
Accept: application/json