services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patientdb
    volumes:
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - medilabo-net

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: notedb
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    healthcheck:
        test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
        interval: 15s
        timeout: 10s
        retries: 10
    networks:
      - medilabo-net
  
  eureka-server:
    image: eureka-server
    hostname: eureka-server  # Force le hostname dans le réseau Docker
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server  # Override pour Eureka
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - medilabo-net

  patient-service:
    build: ./patient-service
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/patientdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: patient-service
      SPRING_APPLICATION_NAME: patient-service
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
        - medilabo-net

  note-service:
    build: ./note-service
    container_name: note-service
    depends_on:
      mongodb:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/notedb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: note-service
      SPRING_APPLICATION_NAME: note-service
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - medilabo-net

  report-service:
    build: ./report-service
    depends_on:
      patient-service:
        condition: service_healthy
      note-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=report-service
      - SPRING_APPLICATION_NAME=report-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - medilabo-net

  gateway:
    build: ./gateway
    depends_on:
      patient-service:
        condition: service_healthy
      note-service:
        condition: service_healthy
      report-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=gateway
      - SPRING_APPLICATION_NAME=gateway
      - JWT_TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1NTg4Nzc1MCwiZXhwIjoxNzU1OTc0MTUwfQ.qf1vek3cvyPL2DgGchycKCZdFxYi7Pvvm4jKZW3GmhvtpoFTSLy37_fOzHsani1ivpQv_fdAhgzf7AfFkbbRzA
    ports:
      - "8083:8083"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - medilabo-net

  frontend-service:
    build: ./frontend-service
    depends_on:
      gateway:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=frontend-service
      - SPRING_APPLICATION_NAME=frontend-service
    ports:
      - "8084:8084"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      - medilabo-net

networks:
  medilabo-net:
    driver: bridge
