server:
  port: 8083

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive  # Force le mode WebFlux
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service
              uri: lb://patient-service:8080
              predicates:
                - Path=/api/patients/**

            - id: note-service
              uri: lb://note-service:8081
              predicates:
                - Path=/api/notes/**

            - id: report-service
              uri: lb://report-service:8082
              predicates:
                - Path=/api/report/**

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
    reactor.netty: DEBUG
    root: INFO



jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30