server:
  port: 8083

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive  # Force le mode WebFlux
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
#          filters:
#            - StripPrefix=1

        - id: note-service
          uri: lb://note-service
          predicates:
            - Path=/api/notes/**
#          filters:
#            - StripPrefix=1

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**
#          filters:
#            - StripPrefix=1

basic:
  auth:
    username: admin
    password: admin

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
    reactor.netty: DEBUG
    root: INFO

jwt:
  secret: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1NTc2MDAzNywiZXhwIjoxNzU1ODQ2NDM3fQ.vnzjKMwPmFm0PtT0MveWQWsWkavZuPHPDq669HDgvQBpNiTcQcZ8ywFZ_DpjObs6wIlA8vCTLpraHbKFPBjEFA