server:
  port: 8083  # Port de la Gateway

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://patient-service:8080
          predicates:
            - Path=/api/patients/**

        - id: note-service
          uri: http://note-service:8081
          predicates:
            - Path=/api/notes/**

        - id: report-service
          uri: http://report-service:8082
          predicates:
            - Path=/api/report/**

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
