spring:
  application:
    #name: gateway-service
    name: gateway
  main:
    web-application-type: reactive  # Force le mode WebFlux
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
#          filters:
#            - StripPrefix=1

        - id: note-service
          uri: lb://note-service
          predicates:
            - Path=/api/notes/**
#          filters:
#            - StripPrefix=1

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**
#          filters:
#            - StripPrefix=1

basic:
  auth:
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#      base-path: /actuator
#  endpoint:
#    health:
#      show-details: always
#      probes:
#        enabled: true

server:
  port: 8083

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
    reactor.netty: DEBUG
    root: INFO

jwt:
  secret: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1NTc2MDAzNywiZXhwIjoxNzU1ODQ2NDM3fQ.vnzjKMwPmFm0PtT0MveWQWsWkavZuPHPDq669HDgvQBpNiTcQcZ8ywFZ_DpjObs6wIlA8vCTLpraHbKFPBjEFA