server:
  port: ${EUREKA_SERVER_PORT}

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # le serveur lui-même ne s'enregistre pas
    fetch-registry: false         # pas besoin de récupérer les autres services