spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: eureka-server

server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  client:
    register-with-eureka: false   # le serveur lui-même ne s'enregistre pas
    fetch-registry: false         # pas besoin de récupérer les autres services