spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}  # Flexible local/Docker
    prefer-ip-address: false
    health-check-url-path: /actuator/health

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/