### 🧪 Get all patients
GET http://localhost:8083/api/patients
Authorization: Basic YWRtaW46YWRtaW4= # admin:admin encodé en Base64
Accept: application/json

### 🧪 Get patient by ID
GET http://localhost:8083/api/patients/1
Authorization: Basic YWRtaW46YWRtaW4=

### 🧪 Create new patient
POST http://localhost:8083/api/patients
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "firstName": "Alice",
  "lastName": "Durand",
  "birthdate": "1985-05-10",
  "gender": "F",
  "address": "45 rue des Lilas, Paris",
  "phone": "0612345678"
}

### 🧪 Update existing patient
PUT http://localhost:8083/api/patients/1
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "firstName": "Alice",
  "lastName": "Durand",
  "birthDate": "1985-05-10",
  "gender": "F",
  "address": "123 avenue Victor Hugo",
  "phone": "0698765432"
}

### 🧪 Get notes for patient
GET http://localhost:8083/api/notes/patient/1
Authorization: Basic YWRtaW46YWRtaW4=

### 🧪 Add note for patient
POST http://localhost:8083/api/notes
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "patientId": "2",
  "content": "Test post"
}

### 🧪 Get report for patient
GET http://localhost:8083/api/report/2
Authorization: Basic YWRtaW46YWRtaW4=

### Delete patient
DELETE http://localhost:8083/api/patients/5
Authorization: Basic YWRtaW46YWRtaW4=

### Obtenir un token JWT
POST http://localhost:8083/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### Test avec Basic Auth
GET http://localhost:8083/api/notes/patient/2
Authorization: Basic YWRtaW46YWRtaW4=

### Test direct sur le service de notes
GET http://localhost:8081/api/notes/patient/2

### Test indirect sur le service de notes
GET http://note-service:8081/api/notes/patient/2

### 1️⃣ Test accès non authentifié
GET http://localhost:8083/api/patients
Accept: application/json

### 2️⃣ Test accès avec user/password
GET http://localhost:8083/api/patients
Accept: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

### 2️⃣ Test accès avec user/password
GET http://localhost:8083/api/report/2
Accept: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

### 3️⃣ Test accès avec admin/admin
GET http://localhost:8083/api/patients
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### 3️⃣ Test accès avec admin/admin
GET http://localhost:8083/api/report/2
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### LOGIN
POST http://localhost:8083/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

### GET patients avec cookie de session
GET http://localhost:8083/api/patients
Accept: application/json
Cookie: JSESSIONID=E0A46B0BEE2DD4090800609338092290


